# docker-image-name: "nsflrose/lrose-cyclone"

# usage 
#  RELEASE_DATE=lrose-cyclone-20190801

FROM ubuntu:18.10 as builder

# ARG RELEASE_DATE

MAINTAINER Bruno Melli "bpmelli@rams.colostate.edu"
LABEL vendor="Joint NCAR CSU"
LABEL release-date="2019-08-01"


COPY checkout_and_build_auto.py /tmp

# Add libs needed to build lrose and run the lrose components

RUN apt-get update && apt-get install -y  \
    libbz2-dev libx11-dev libfftw3-dev \
    qtdeclarative5-dev libqt5webview5-dev git rsync \
    gcc g++ gfortran chrpath \
    automake make libtool pkg-config libexpat1-dev python \
    cmake libgeographic-dev libeigen3-dev libzip-dev libcurl4-openssl-dev \
    libpng-dev libarmadillo-dev libopenmpi-dev 
    
WORKDIR /tmp

RUN ln -s -f /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /usr/bin/qmake-qt5 

# ARG RELEASE_DATE

RUN export LROSE_INSTALL_DIR=/usr/local/lrose

# 
# lrose-core
#

RUN /tmp/checkout_and_build_auto.py --debug --prefix $LROSE_INSTALL_DIR --clean --logDir /tmp/my_lrose_log 
# --releaseDate $RELEASE_DATE

#
# fractl
#

RUN git clone https://github.com/mmbell/fractl.git && \
    cd fractl && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=$LROSE_INSTALL_DIR . && \
    make && \
    make install

#
# samurai
#

WORKDIR /tmp

RUN git clone https://github.com/mmbell/samurai.git && \
    cd samurai && \
    /usr/bin/cmake3 -DCMAKE_INSTALL_PREFIX:PATH=$LROSE_INSTALL_DIR . && \
    make && \
    make install

#
# vortrac
#
# WORKDIR /tmp2

#          name: Add to Environment Variables for vortrac
#          command: |
RUN export RADX_INCLUDE=$LROSE_INSTALL_DIR/include && \
    export RADX_LIB=$LROSE_INSTALL_DIR/lib && \
    export ARMADILLO_INCLUDE=`pkg-config --variable=includedir armadillo` && \
    export ARMADILLO_LIB=`pkg-config --variable=libdir armadillo` && \
    export NETCDF_INCLUDE=`pkg-config --variable=includedir netcdf` && \
    export NETCDF_LIB=`pkg-config --variable=libdir netcdf` && \
    export QT5_BIN=/usr/lib64/qt5/bin && \
    export LD_LIBRARY_PATH=/usr/local/lrose/lib && \

 RUN git clone https://github.com/mmbell/vortrac.git && \
     cd vortrac/src && \
     $QT5_BIN/qmake . && \
     make && \
     cp vortrac $LROSE_INSTALL_DIR/bin && \
     cd .. && \
     rsync -av Resources $LROSE_INSTALL_DIR


#     cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/lrose . && \
#     make install
    
    
# Set runpath

WORKDIR /usr/local/lrose/lib
RUN chrpath -k -r /usr/local/lrose/lib *.so || true

WORKDIR /usr/local/lrose/bin
RUN chrpath -k -r /usr/local/lrose/lib * || true

# Start from a fresh ubuntu to not carry over all the build stuff

FROM ubuntu:18.10

# Copy the lrose build

ADD VERSION .
COPY --from=builder /usr/local/lrose/ /usr/local/lrose/

WORKDIR /home/lrose

RUN apt-get update && apt-get install -y \
    libqt5gui5 libqt5core5a libqt5qml5 qt5-default libx11-6 \
    libfftw3-3 libgeographic17 \
    libfreetype6 libcurl4 && \
    rm -rf /var/lib/apt/lists/* && \
    useradd -G video lrose

ENV PATH /usr/local/lrose/bin:$PATH
